//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pk_config
    {
        public pk_config()
        {
            this.pk_config_log = new HashSet<pk_config_log>();
        }
    
        public int id { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    
        public virtual ICollection<pk_config_log> pk_config_log { get; set; }
    }
}
