//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pk_loging_history
    {
        public long Id { get; set; }
        public int user_id { get; set; }
        public System.DateTime login_date { get; set; }
        public System.DateTime logout_date { get; set; }
    }
}
