//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pk_users
    {
        public pk_users()
        {
            this.pk_loging_history = new HashSet<pk_loging_history>();
            this.pk_vehicle_out = new HashSet<pk_vehicle_out>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<sbyte> activate { get; set; }
        public Nullable<sbyte> active { get; set; }
        public string avatar { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> date_register { get; set; }
        public Nullable<System.DateTime> last_login { get; set; }
        public string role { get; set; }
    
        public virtual ICollection<pk_loging_history> pk_loging_history { get; set; }
        public virtual ICollection<pk_vehicle_out> pk_vehicle_out { get; set; }
    }
}
