//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pk_users
    {
        public long Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public bool activate { get; set; }
        public bool active { get; set; }
        public string avatar { get; set; }
        public string phone { get; set; }
        public System.DateTime date_register { get; set; }
        public System.DateTime last_login { get; set; }
        public string role { get; set; }
    }
}
