//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblin
    {
        public int InId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> TicketId { get; set; }
    
        public virtual tblticket tblticket { get; set; }
    }
}
