//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblticket
    {
        public tblticket()
        {
            this.tblins = new HashSet<tblin>();
            this.tblouts = new HashSet<tblout>();
        }
    
        public int TicketId { get; set; }
        public string Barcode { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<tblin> tblins { get; set; }
        public virtual ICollection<tblout> tblouts { get; set; }
    }
}
