//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public tbluser()
        {
            this.tblouts = new HashSet<tblout>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<tblout> tblouts { get; set; }
    }
}
