//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parkingEntities : DbContext
    {
        public parkingEntities()
            : base("name=parkingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbluser> tblusers { get; set; }
        public DbSet<tblin> tblins { get; set; }
        public DbSet<tblout> tblouts { get; set; }
        public DbSet<tblticket> tbltickets { get; set; }
    }
}
