//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleParking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parkingsEntities : DbContext
    {
        public parkingsEntities()
            : base("name=parkingsEntities")
        {
        }

        public parkingsEntities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<pk_config> pk_config { get; set; }
        public DbSet<pk_config_log> pk_config_log { get; set; }
        public DbSet<pk_loging_history> pk_loging_history { get; set; }
        public DbSet<pk_users> pk_users { get; set; }
        public DbSet<pk_vehicle_in> pk_vehicle_in { get; set; }
        public DbSet<pk_vehicle_out> pk_vehicle_out { get; set; }
    }
}
